name: build
on: [push]
jobs:
  build-hotspot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 12, 13, 14, 15, 16 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - run: ./gradlew assemble check --info
  build-graalvm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11 ]
    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: ${{ matrix.java-version }}
          graalvm-version: 21.1.0
          native-image: true
      - run: ./gradlew assemble check nativeImage --info