name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 12, 13, 14, 15, 16, 17 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      # delete gradle.properties in Java 8 because it contains a then-unsupported JVM argument: --add-exports
      - run: rm java/gradle.properties
        if: ${{ matrix.java-version == 8 }}
      - run: ./gradlew assemble check --info
  android_tests:
    runs-on: macos-latest
    strategy:
      matrix:
        api-version: [19,23,29]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      
      # append settings.gradle_android (includes :android) only when doing Android tests because the Android plugin requires Java 11+,
      #   and ALSO, for some reason github ci is throwing "java.lang.OutOfMemoryError: Metaspace" on :java:spotlessScala when Android is included,
      #   and it's not really necessary for the Java compilation, so.  Out it goes.
      - run: cat settings.gradle_android >> settings.gradle
      - name: Android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-version }}
          script: ./gradlew :android:connectedAndroidTest --info
